services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - /home/eu/Downloads/csv_teste:/docker-entrypoint-initdb.d
